### ISSUE TITLE
onCancel hold event never called

### ISSUE THREAD

**Issue by squarest** [dewarder/CameraButton#3]
I enjoy your button. But i need to cancel video recording when user release button earlier MAX_HOLD_DURATION.
But onCancel event not called.
`cameraButton = findViewById(R.id.camera_button);
        cameraButton.setMode(CameraButton.Mode.HOLD);
        cameraButton.setHoldDuration(MAX_DURATION);
        cameraButton.setProgressArcColors(new int[]{getResources().getColor(R.color.lightblue),
                getResources().getColor(R.color.lightblue)});
        camera.addCameraListener(new CameraListener() {
            @Override
            public void onVideoTaken(File video) {
                if (videoTaken) {
                    Intent intent = new Intent();
                    intent.putExtra("videoSelfie", video.getAbsolutePath());
                    setResult(RESULT_OK, intent);
                    finish();
                }
            }
        });
        cameraButton.setOnHoldEventListener(new CameraButton.OnHoldEventListener() {
            @Override
            public void onStart() {
                camera.startCapturingVideo(null, MAX_DURATION);
            }

            @Override
            public void onFinish() {
                videoTaken = true;
                camera.stopCapturingVideo();
            }

            @Override
            public void onCancel() {
                camera.stopCapturingVideo();
                Toast.makeText(CameraActivity.this, R.string.selfie_error, Toast.LENGTH_SHORT).show();
            }
        });`

**Comment by hluhovskyi** [comment]
Added in version 2.0.0. Thanks!
